import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,authorization,apikey","Access-Control-Allow-Methods":"POST,OPTIONS"};
const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...C,"Content-Type":"application/json","Cache-Control":"no-store"}});
async function F(path:string){const h={apikey:K,Authorization:`Bearer ${K}`};let r=await fetch(`${U}/rest/v1/${path}`,{headers:h});let t=await r.text();if(!r.ok&&r.status===401&&t.includes("JWT issued at future")){await new Promise(x=>setTimeout(x,850));r=await fetch(`${U}/rest/v1/${path}`,{headers:h});t=await r.text()}if(!r.ok)throw Error(`${r.status} ${t.slice(0,500)}`);return t?JSON.parse(t):[]}
function canon(s:string){return s.toLowerCase().replace(/[^a-z0-9]/g,"")}
type Desired={name:string,weight:number,reason:string};
function desiredCategories(text:string){const t=text.toLowerCase();const out:Desired[]=[];const add=(name:string,weight:number,reason:string)=>{const x=out.find(v=>v.name===name);if(!x)out.push({name,weight,reason});else x.weight=Math.max(x.weight,weight)};
 const bridge=/bridge|elevated guideway|guideway|pier|abutment|girder|piling|wingwall|deck anchorage|elevated rail/.test(t);
 const road=/\broad\b|roadwork|streetscape|paving|pathway|highway|\bhwy\b/.test(t);
 const building=/building|facility|housing|school|station/.test(t);
 const concrete=/concrete|slab|footing|foundation|sidewalk|pad|plinth/.test(t);
 const demo=/demolition|removal|decommission/.test(t);
 const earth=/excavat|earthwork|site preparation|cut\/fill|grading/.test(t);
 const utility=/underground|water main|sanitary|storm sewer|utility|drainage|duct bank/.test(t);
 if(bridge){add("Bridges New Construction",45,"Major bridge/elevated-structure capacity");add("Bridge Rehabilitation",24,"Bridge structural experience");add("Earthworks",10,"Associated civil/site scope");if(concrete)add("Concrete Road/Sidewalk works",8,"Concrete/site capacity")}
 if(building&&!bridge)add("Buildings General Contractor",32,"Building/facility prime capacity");
 if(demo)add("Demolition Contractor",22,"Demolition/removal capacity");
 if(earth)add("Earthworks",bridge?12:25,"Earthworks/site preparation capacity");
 if(utility){add("Water Main, Sanitary Sewer and Storm Sewer Install/Replace",22,"Underground utility capacity");add("Landfill Earthworks and Underground Utilities",14,"Underground/civil capacity")}
 if(road&&!bridge){add("Road Construction",30,"Road/corridor prime capacity");add("Asphalt Road Works",12,"Road-surface capacity")}
 if(concrete&&!bridge)add("Concrete Road/Sidewalk works",18,"Concrete/site capacity");
 if(!out.length)add("Buildings General Contractor",10,"Broad construction capacity");return{out,projectType:bridge?"bridge_elevated_structure":road?"road_civil":building?"building":demo?"demolition":earth?"earthworks":"general_construction"}}
function categoryMatch(category:string,name:string){return category.toLowerCase().includes(name.toLowerCase())}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:C});if(req.method!=="POST")return J({error:"POST required"},405);try{const b=await req.json();const id=String(b.signal_id||"");if(!id)return J({error:"signal_id required"},400);const sig=(await F(`signals?id=eq.${encodeURIComponent(id)}&select=id,title,summary,region,signal_type,source_url,organization`))?.[0];if(!sig)return J({error:"signal not found"},404);const text=`${sig.title||""} ${sig.summary||""}`;const model=desiredCategories(text);const desired=model.out;const [dir,awards]=await Promise.all([F("prime_contractor_directory?select=company_name,category,valid_as_of,source_url&limit=2500"),F("contract_awards?select=title,buyer,supplier_name,region,award_value,publication_date,source_url&supplier_name=not.is.null&limit=1200")]);
 const map=new Map<string,any>();for(const r of dir||[]){const key=canon(r.company_name);if(!key)continue;let x=map.get(key)||{company:r.company_name,categories:new Set<string>(),matched:new Map<string,number>(),award_count:0,award_value:0,awards:[],score:0};x.categories.add(r.category);for(const d of desired)if(categoryMatch(String(r.category),d.name))x.matched.set(d.name,Math.max(x.matched.get(d.name)||0,d.weight));map.set(key,x)}
 for(const a of awards||[]){if(!a.supplier_name)continue;const key=canon(a.supplier_name);let x=map.get(key);if(!x){x={company:a.supplier_name,categories:new Set<string>(),matched:new Map<string,number>(),award_count:0,award_value:0,awards:[],score:0};map.set(key,x)}x.award_count++;x.award_value+=Number(a.award_value||0);x.awards.push({title:a.title,buyer:a.buyer,value:Number(a.award_value||0),date:a.publication_date,source_url:a.source_url})}
 const out:any[]=[];for(const x of map.values()){const matched=[...x.matched.entries()].map(([name,weight])=>({name,weight}));const capacity=[...x.categories].filter((c:string)=>/Bridge|Buildings General Contractor|Demolition|Earthworks|Concrete Road\/Sidewalk|Water Main|Road Construction|Underground Utilities/.test(c));let score=matched.reduce((s:any,m:any)=>s+Number(m.weight),0);const hasPrimary=matched.some((m:any)=>Number(m.weight)>=30);if(hasPrimary)score+=12;score+=Math.min(14,x.award_count*6);if(x.awards.some((a:any)=>/alberta|calgary|edmonton|banff|red deer|innisfail|tofield/i.test(`${a.title} ${a.region||""}`)))score+=5;if(model.projectType==="bridge_elevated_structure"&&!matched.some((m:any)=>/Bridge/.test(m.name)))score-=18;if(!matched.length&&!x.award_count)continue;score=Math.max(0,Math.min(100,score));if(score<18)continue;const matchedNames=matched.sort((a:any,b:any)=>b.weight-a.weight).map((m:any)=>m.name);out.push({company:x.company,score,project_type:model.projectType,matched_categories:matchedNames,capacity_categories:capacity.slice(0,10),award_history:{count:x.award_count,total_value:x.award_value,recent:x.awards.sort((a:any,b:any)=>String(b.date).localeCompare(String(a.date))).slice(0,4)},why:matchedNames.length?`Capacity match for ${model.projectType}: ${matchedNames.join(", ")}${x.award_count?`; ${x.award_count} Alberta construction award record(s) in memory.`:"."}`:`Has ${x.award_count} Alberta construction award record(s) in current award memory.`})}
 out.sort((a,b)=>b.score-a.score||b.award_history.total_value-a.award_history.total_value);return J({signal:{id:sig.id,title:sig.title,region:sig.region,source_url:sig.source_url,organization:sig.organization},project_type:model.projectType,scope_categories:desired,interpretation:"Potential prime/partner candidates are ranked from current City of Calgary prequalification categories plus Alberta federal award memory. This is capacity evidence, not a prediction that a firm will bid or win this specific project.",partners:out.slice(0,15)})}catch(e){return J({error:String(e)},500)}});
