import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get('SUPABASE_URL')!,A=Deno.env.get('SUPABASE_ANON_KEY')!;
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,x-client-info,apikey,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
async function call(slug:string,auth:string,body:any={}){const r=await fetch(`${U}/functions/v1/${slug}`,{method:'POST',headers:{apikey:A,Authorization:auth,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(90000)});const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d={raw:t.slice(0,800)}}if(!r.ok)throw Error(`${slug} ${r.status}: ${t.slice(0,600)}`);return d}
function decisionFor(module:string){if(module==='construction')return'INVESTIGATE';if(module==='procurement')return'INVESTIGATE';if(module==='business_growth')return'INVESTIGATE_GROWTH';if(module==='grants_funding')return'VERIFY_ELIGIBILITY';if(module==='education_skills')return'BUILD_CAPABILITY';if(module==='career_income')return'INVESTIGATE_ROLE';return'INVESTIGATE'}
function proactiveFallback(selfModel:any,active:Set<string>,reason:string){const goal=selfModel?.goal||{},domain=String(goal.domain||''),attention=Math.max(15,Math.min(45,Number(selfModel?.attention_budget_minutes||30))),growth=domain==='business_growth'||active.has('business_growth')||active.has('construction');if(growth){const module=active.has('business_growth')?'business_growth':active.has('construction')?'construction':null;return{decision:'DIAGNOSE',strategy_path:'YOU_TO_WORLD',module_code:module,confidence:80,title:'Find the bottleneck in the profitable-project pipeline',action:`Use the next ${attention} minutes to capture the missing operating evidence that cannot be recovered from connected sources.`,why:`${reason} The highest-value internal move is to reduce uncertainty without consuming capital.`,expected_output:'A ranked growth bottleneck and one measurable intervention.',capital_required:0,attention_minutes:attention}}return{decision:'DIAGNOSE',strategy_path:'UNKNOWN_TO_LEARN',module_code:active.has(domain)?domain:null,confidence:76,title:'Identify the constraint preventing the active goal from moving',action:`Use the next ${attention} minutes to capture the minimum missing evidence needed to identify the binding constraint.`,why:reason,expected_output:'A testable bottleneck hypothesis.',capital_required:0,attention_minutes:attention}}
function isDiagnostic(x:any){const t=String(x?.title||'').toLowerCase(),type=String(x?.type||x?.opportunity_type||'').toLowerCase();return /bottleneck|diagnos|capture the last 90 days/.test(t)||type==='growth_diagnostic'}
function isExternal(x:any){const type=String(x?.type||x?.opportunity_type||'').toLowerCase(),m=String(x?.module_code||'');return ['direct_bid','subcontract_pipeline'].includes(type)||['construction','procurement'].includes(m)}
function isPipeline(x:any){const type=String(x?.type||x?.opportunity_type||'').toLowerCase(),title=String(x?.title||'').toLowerCase();return type==='existing_pipeline'||title.startsWith('follow up:')}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(!['GET','POST'].includes(req.method))return J({error:'GET or POST required'},405);const auth=req.headers.get('Authorization')||'';if(!auth)return J({error:'Missing bearer token'},401);try{
let hygiene:any=null;try{hygiene=await call('candidate-hygiene',auth,{})}catch(e){hygiene={ok:false,error:String(e).slice(0,300)}}
const [base,router]=await Promise.all([call('strategy-core',auth,{}),call('intelligence-router',auth,{})]);let cognition:any=null;try{cognition=await call('cognitive-engine',auth,{})}catch(e){cognition={ok:false,error:String(e).slice(0,500)}}let reasoning:any=null;try{reasoning=await call('reasoning-core',auth,{cognition})}catch(e){reasoning={ok:false,error:String(e).slice(0,500)}}let simulation:any=null;try{simulation=await call('future-simulator',auth,{persist:false})}catch(e){simulation={ok:false,error:String(e).slice(0,500)}}const active=new Set<string>((router.active||[]).map((x:any)=>String(x.code))),watch=new Set<string>((router.watch||[]).map((x:any)=>String(x.code)));if(!base?.strategy)return J({...base,alignment_guard:{active_modules:[...active],watch_modules:[...watch],hygiene}},200);
const strat=base.strategy,top=strat.next_best_move||{},validPortfolio=(strat.portfolio||[]).filter((x:any)=>active.has(String(x.module_code))).sort((a:any,b:any)=>Number(b.score||0)-Number(a.score||0));const horizons:any={};for(const [k,rows] of Object.entries(strat.horizons||{}))horizons[k]=(Array.isArray(rows)?rows:[]).filter((x:any)=>active.has(String(x.module_code)));
let next=top,sequence=strat.sequence||null,replaced=false,proactive=false,tieBreak=false,pipelinePriority=false;
if(top?.module_code&&!active.has(String(top.module_code))){replaced=true;const alt=validPortfolio.find((x:any)=>Number(x.score||0)>=62);if(alt)next={decision:decisionFor(String(alt.module_code)),module_code:alt.module_code,confidence:Number(alt.confidence||75),title:alt.title,action:alt.next_action||'Investigate before committing resources.',candidate_id:alt.id,score:Number(alt.score||0),why:'Highest currently active-domain strategy option after stale candidates were removed.'};else{next=proactiveFallback(base.self_model,active,'The previous top option belonged to an inactive intelligence domain and no active external candidate clears the threshold.');proactive=true}sequence=null}
if(next?.decision==='DO_NOTHING'){next=proactiveFallback(base.self_model,active,'No current external candidate clears the common action threshold.');sequence=null;proactive=true}
// Owned-pipeline priority: a real open quote/submission is closer to revenue than a newly discovered opportunity or generic diagnostic.
if(!isPipeline(next)){const currentScore=Number(next?.score||validPortfolio.find((x:any)=>x.id===next?.candidate_id)?.score||0),currentConfidence=Number(next?.confidence||validPortfolio.find((x:any)=>x.id===next?.candidate_id)?.confidence||0);const pipeline=validPortfolio.find((x:any)=>isPipeline(x)&&Number(x.score||0)>=currentScore-5&&Number(x.confidence||0)>=80);if(pipeline){const old=next;next={decision:'FOLLOW_UP',strategy_path:'YOU_TO_WORLD',module_code:pipeline.module_code,confidence:Number(pipeline.confidence||90),title:pipeline.title,action:pipeline.next_action||'Follow up the live opportunity and verify economics before commitment.',candidate_id:pipeline.id,score:Number(pipeline.score||0),why:'This is already in the user’s observed operating pipeline and is materially closer to revenue than a newly discovered opportunity. Quoted value is not treated as won revenue, and the margin gate still applies.'};const steps:any[]=[{order:1,label:'NOW',candidate_id:pipeline.id,module_code:pipeline.module_code,title:pipeline.title,action:pipeline.next_action||'Follow up the live opportunity.',why:'Existing owned pipeline is closer to revenue and has direct user-specific evidence.'}];if(old?.candidate_id&&old.candidate_id!==pipeline.id)steps.push({order:2,label:'NEXT',candidate_id:old.candidate_id,module_code:old.module_code,title:old.title,action:old.action,why:'Preserve the previously highest-ranked move after the live pipeline follow-up is qualified.'});sequence={steps,reason:'Owned-pipeline priority: convert or disqualify live opportunities before spending attention on equally ranked discovery.'};pipelinePriority=true}}
// Evidence-aware tie-break: a data-gathering diagnostic must not crowd out a near-tied, higher-confidence external opportunity.
if(isDiagnostic(next)){const diagnosticScore=Number(next.score||validPortfolio.find((x:any)=>x.id===next.candidate_id)?.score||0),diagnosticConfidence=Number(next.confidence||validPortfolio.find((x:any)=>x.id===next.candidate_id)?.confidence||0);const external=validPortfolio.find((x:any)=>isExternal(x)&&!isDiagnostic(x)&&Number(x.score||0)>=diagnosticScore-4&&Number(x.confidence||0)>=diagnosticConfidence+8);if(external){const old=next;next={decision:decisionFor(String(external.module_code)),module_code:external.module_code,confidence:Number(external.confidence||75),title:external.title,action:external.next_action||'Verify the opportunity before committing estimating time or capital.',candidate_id:external.id,score:Number(external.score||0),why:`A real external opportunity is near-tied on strategy score but has materially stronger evidence confidence (${Number(external.confidence||0)}% vs ${diagnosticConfidence}%). Handle the time-sensitive external move first; keep the internal diagnostic next.`};sequence={steps:[{order:1,label:'NOW',candidate_id:external.id,module_code:external.module_code,title:external.title,action:external.next_action||'Verify the opportunity.',why:'Near-tied external opportunity with materially stronger evidence confidence.'},{order:2,label:'NEXT',candidate_id:old.candidate_id,module_code:old.module_code,title:old.title,action:old.action,why:'Internal diagnostic remains valuable, but it should not displace a stronger real-world opportunity.'}],reason:'Evidence-aware tie-break: external action first, internal learning second.'};tieBreak=true}}
// Cognitive reasoning layer: counterfactuals, contradiction checks, information value and opportunity cost can override raw score ordering.
let cognitiveOverride=false;
if(cognition?.ok&&Array.isArray(cognition.assessments)){
  const ranked=cognition.assessments.filter((x:any)=>x&&x.candidate_id&&x.decision!=='REJECT'&&active.has(String(x.module_code)));
  const pick=ranked.find((x:any)=>validPortfolio.some((p:any)=>p.id===x.candidate_id));
  if(pick&&Number(pick.intellectual_priority||0)>=45){
    const pc=validPortfolio.find((p:any)=>p.id===pick.candidate_id);
    if(pc){
      const d=pick.decision==='LEARN'?'DIAGNOSE':pick.decision==='WAIT'?'WATCH':pick.decision;
      next={decision:d,strategy_path:pick.decision==='LEARN'?'UNKNOWN_TO_LEARN':isPipeline(pc)?'YOU_TO_WORLD':'WORLD_TO_YOU',module_code:pc.module_code,confidence:Number(pick.confidence||pc.confidence||70),title:pc.title,action:pick.recommended_action||pc.next_action||'Take the smallest reversible step that resolves the key uncertainty.',candidate_id:pc.id,score:Number(pc.score||0),intellectual_priority:Number(pick.intellectual_priority||0),why:pick.rationale?.summary||'Selected by the cognitive reasoning layer after testing uncertainty, opportunity cost and counterfactuals.',cognition:{success_probability:pick.success_probability??null,expected_value:pick.expected_value??null,expected_value_currency:pick.expected_value_currency||null,information_value:pick.information_value??null,reversibility:pick.reversibility??null,urgency:pick.urgency??null,opportunity_cost:pick.opportunity_cost??null,goal_contribution:pick.goal_contribution??null,unknowns:(pick.unknowns||[]).slice(0,4),contradictions:(pick.contradictions||[]).slice(0,4),causal_model:pick.causal_model||null,counterfactuals:(pick.counterfactuals||[]).slice(0,4)}};
      const alt=ranked.find((x:any)=>x.candidate_id!==pick.candidate_id&&validPortfolio.some((p:any)=>p.id===x.candidate_id));
      if(alt){const ac=validPortfolio.find((p:any)=>p.id===alt.candidate_id);sequence={steps:[{order:1,label:'NOW',candidate_id:pc.id,module_code:pc.module_code,title:pc.title,action:next.action,why:'Highest reasoning priority after uncertainty, causal path, reversibility and opportunity-cost analysis.'},{order:2,label:'NEXT',candidate_id:ac.id,module_code:ac.module_code,title:ac.title,action:alt.recommended_action||ac.next_action||'Re-evaluate after the current uncertainty is resolved.',why:'Second-best non-dominated path under the same reasoning model.'}],reason:'Cognitive ordering: choose the move with the strongest decision quality, not merely the highest raw opportunity score.'}}
      cognitiveOverride=true;
    }
  }
}
let reasoningOverride=false;
if(reasoning?.ok&&reasoning?.recommendation?.candidate_id){
  const rr=reasoning.recommendation,pc=validPortfolio.find((p:any)=>p.id===rr.candidate_id);
  if(pc&&active.has(String(pc.module_code))&&Number(reasoning?.robustness?.score||0)>=45){
    const rd=rr.decision==='LEARN'?'DIAGNOSE':rr.decision==='WAIT'?'WATCH':rr.decision;
    next={decision:rd,strategy_path:rr.decision==='LEARN'?'UNKNOWN_TO_LEARN':isPipeline(pc)?'YOU_TO_WORLD':'WORLD_TO_YOU',module_code:pc.module_code,confidence:Number(rr.confidence||pc.confidence||70),title:pc.title,action:rr.action||pc.next_action||'Take the smallest reversible step.',candidate_id:pc.id,score:Number(pc.score||0),intellectual_priority:Number(rr.intellectual_priority||0),why:rr.reason||'Selected by the meta-reasoning layer after testing competing hypotheses and counterfactuals.',reasoning:{version:reasoning.reasoning_version||null,robustness:reasoning.robustness||null,thesis:reasoning.thesis||null,uncertainties:(reasoning.uncertainties||[]).slice(0,4),what_would_change_mind:(reasoning.what_would_change_mind||[]).slice(0,4),counterfactuals:(reasoning.counterfactuals||[]).slice(0,4),hypotheses:(reasoning.hypotheses||[]).slice(0,3),reasoning_run_id:reasoning.reasoning_run_id||null}};
    reasoningOverride=true;
  }
}
let simulationOverride=false;
if(simulation?.ok&&simulation?.preferred_scenario&&next?.candidate_id){
  const scenarios=Array.isArray(simulation.scenarios)?simulation.scenarios:[],preferred=simulation.preferred_scenario,runner=scenarios.find((x:any)=>x.id!==preferred.id);
  const gap=Number(preferred.robust_utility||0)-Number(runner?.robust_utility||0),material=gap>=8&&Number(preferred.evidence_confidence||0)>=45;
  const simTrace={engine_version:simulation.engine_version||null,preferred_scenario:preferred.id,robust_utility:Number(preferred.robust_utility||0),runner_up:runner?.id||null,utility_gap:Number(gap.toFixed(1)),material_override:material,projection:preferred.twin_projection||[],uncertainty:simulation.uncertainty||null};
  if(material&&preferred.id==='LEARN_FIRST'){
    next={...next,decision:'INVESTIGATE',strategy_path:'UNKNOWN_TO_LEARN',action:next.action||'Resolve the highest-value unknown with the smallest reversible information action before commitment.',why:'Future-state simulation shows that reducing uncertainty preserves more optionality and lowers regret before commitment.',simulation:simTrace};
    simulationOverride=true;
  }else if(material&&preferred.id==='HOLD'){
    next={...next,decision:'WATCH',strategy_path:'UNKNOWN_TO_LEARN',action:'Preserve capital and attention for now; re-evaluate when new evidence arrives or the opportunity window materially changes.',why:'Future-state simulation shows that immediate commitment has materially higher regret than preserving state.',simulation:simTrace};
    simulationOverride=true;
  }else if(material&&preferred.id==='ALTERNATIVE'&&preferred.candidate_id){
    const alt=validPortfolio.find((p:any)=>p.id===preferred.candidate_id);
    if(alt){next={decision:isPipeline(alt)?'FOLLOW_UP':'INVESTIGATE',strategy_path:isPipeline(alt)?'YOU_TO_WORLD':'WORLD_TO_YOU',module_code:alt.module_code,confidence:Number(alt.confidence||70),title:alt.title,action:alt.next_action||'Take the smallest reversible next step on the more robust alternative.',candidate_id:alt.id,score:Number(alt.score||0),why:'Counterfactual simulation shows the alternative produces a materially more robust Twin state under current assumptions.',simulation:simTrace};simulationOverride=true;}
  }else next={...next,simulation:simTrace};
}
if(sequence?.steps?.length){const mods=sequence.steps.map((x:any)=>String(x.module_code||''));if(mods.some((m:string)=>m&&!active.has(m)))sequence=null}
const shield={...(strat.attention_shield||{}),surfaced:validPortfolio.length+(proactive?1:0),suppressed:Math.max(Number(strat.attention_shield?.suppressed||0),Math.max(0,Number(strat.attention_shield?.input_candidates||0)-validPortfolio.length))};return J({...base,strategy:{...strat,next_best_move:next,sequence,portfolio:validPortfolio,horizons,attention_shield:shield},alignment_guard:{version:'decision_engine_v10_counterfactual_simulation',replaced_inactive_top:replaced,proactive_fallback:proactive,owned_pipeline_priority_applied:pipelinePriority,evidence_tiebreak_applied:tieBreak,cognitive_override_applied:cognitiveOverride,reasoning_override_applied:reasoningOverride,simulation_override_applied:simulationOverride,cognitive_engine:cognition?.engine_version||null,reasoning_engine:reasoning?.reasoning_version||null,simulation_engine:simulation?.engine_version||null,active_modules:[...active],watch_modules:[...watch],hygiene,principle:'Raw scores are subordinate to cognition. PIOS forms a thesis, exposes uncertainty, compares counterfactuals, simulates future Twin states, tests disconfirming evidence and changes course only when an alternative is materially more robust.'}})}catch(e){return J({error:String(e)},500)}});