import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
async function R(path:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set('apikey',K);h.set('Authorization',`Bearer ${K}`);if(init.body)h.set('Content-Type','application/json');let r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:h});let t=await r.text();if(!r.ok&&r.status===401&&t.includes('JWT issued at future')){await new Promise(x=>setTimeout(x,850));r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:h});t=await r.text()}if(!r.ok)throw Error(`${r.status} ${t.slice(0,500)}`);return t?JSON.parse(t):null}
const norm=(s:string)=>s.replace(/^\uFEFF/,'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const n=(v:any)=>{const x=Number(String(v??'').replace(/[$,]/g,''));return Number.isFinite(x)?x:null};
function annual(per:string,min:any,max:any){let lo=n(min),hi=n(max);if(lo==null&&hi==null)return{lo:null,hi:null};const p=String(per||'').toLowerCase();let m=1;if(p.includes('hour'))m=2080;else if(p.includes('day'))m=260;else if(p.includes('week'))m=52;else if(p.includes('month'))m=12;else if(p.includes('year')||p.includes('annual'))m=1;else return{lo:null,hi:null};return{lo:lo==null?null:Math.round(lo*m),hi:hi==null?null:Math.round(hi*m)}}
function isoDate(v:string){const m=String(v||'').match(/(\d{4})[\/-](\d{2})[\/-](\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}T00:00:00Z`:null}
async function upsertSignals(rows:any[]){if(!rows.length)return;await R('signals?on_conflict=source_id,external_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)})}

async function piosCronSecret(){const r=await fetch(`${U}/rest/v1/system_secrets?name=eq.scheduled_intelligence&select=secret`,{headers:{apikey:K,Authorization:`Bearer ${K}`}});if(!r.ok)return "";const a=await r.json();return a?.[0]?.secret||""}
function piosSafe(a:string,b:string){if(!a||!b||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function piosAuthorized(req:Request){return piosSafe(req.headers.get("x-pios-cron-token")||"",await piosCronSecret())}

Deno.serve(async(req)=>{if(req.method!=='POST')return J({error:'POST required'},405);if(!(await piosAuthorized(req)))return J({error:'unauthorized'},401);let src:any=null;try{src=(await R('world_sources?code=eq.jobbank_monthly&select=*'))?.[0];if(!src)return J({error:'world source not configured'},500);if(src.last_success_at&&Date.now()-new Date(src.last_success_at).getTime()<18*3600*1000)return J({ok:true,skipped:true,reason:'source refreshed within 18 hours',last_success_at:src.last_success_at});const metaR=await fetch(src.endpoint_url,{headers:{'User-Agent':'Personal-Intelligence-OS/1.0'},signal:AbortSignal.timeout(15000)});if(!metaR.ok)throw Error(`metadata HTTP ${metaR.status}`);const meta=await metaR.json();const resources=(meta?.result?.resources||[]).filter((x:any)=>String(x.format||'').toUpperCase()==='CSV');const en=resources.filter((x:any)=>/english/i.test(String(x.name||x.title||''))||String(x.language||'').toLowerCase().includes('en'));const latest=(en.length?en:resources).sort((a:any,b:any)=>String(b.created||b.last_modified||'').localeCompare(String(a.created||a.last_modified||'')))[0];if(!latest?.url)throw Error('No English CSV resource found');const csv=await fetch(latest.url,{headers:{'User-Agent':'Personal-Intelligence-OS/1.0'},signal:AbortSignal.timeout(30000)});if(!csv.ok||!csv.body)throw Error(`CSV HTTP ${csv.status}`);const reader=csv.body.getReader(),dec=new TextDecoder('utf-16le');let buffer='',headers:string[]|null=null,idx:any={},scanned=0,matched=0,stored=0,batch:any[]=[];const homepage=src.homepage_url||latest.url;
const processLine=async(line:string)=>{line=line.replace(/\r$/,'');if(!line)return;if(!headers){headers=line.split('\t').map(norm);headers.forEach((h,i)=>idx[h]=i);return}scanned++;const c=line.split('\t'),get=(...names:string[])=>{for(const name of names){const i=idx[norm(name)];if(i!==undefined)return String(c[i]??'').trim()}return''};const prov=get('Province/Territory');if(prov.toLowerCase()!=='alberta')return;matched++;if(stored>=4000)return;const id=get('WIC Job Location Snapshot ID')||`${latest.id}:${scanned}`,title=get('Job Title')||get('Original Job Title')||'Job posting',noc=get('NOC21 Code'),nocName=get('NOC21 Code Name')||get('NOC 2016 Code Name'),city=get('City'),first=get('First Posting Date'),vac=get('Vacancy Count'),empType=get('Employment Type'),term=get('Employment Term'),edu=get('Education LOS'),exp=get('Experience Level'),salaryPer=get('Salary Per'),salaryMin=get('Salary Minimum'),salaryMax=get('Salary Maximum'),official=get('Official Language');const a=annual(salaryPer,salaryMin,salaryMax);const salaryText=(salaryMin||salaryMax)?[salaryMin,salaryMax].filter(Boolean).join('–')+` per ${salaryPer||'period'}`:'Not stated';const summary=[nocName?`NOC ${noc}: ${nocName}`:'',city?`Location: ${city}, Alberta`:'Alberta',empType?`Employment: ${empType}`:'',term?`Term: ${term}`:'',edu&&edu!=='NA'?`Education: ${edu}`:'',exp&&exp!=='NA'?`Experience: ${exp}`:'',`Salary: ${salaryText}`,vac?`Vacancies: ${vac}`:''].filter(Boolean).join(' | ');batch.push({source_id:src.id,external_id:`jobbank:${id}`,signal_type:'career_job_posting',title,summary,organization:null,region:'Alberta',locality:city||null,published_at:isoDate(first),deadline_at:null,source_url:homepage,verified_facts:[`Published in the ${latest.name||'latest'} national Job Bank open-data file.`,`Province/Territory: Alberta.`,city?`City: ${city}.`:'Alberta location.',noc?`NOC 2021 code: ${noc}.`:'',`Salary field: ${salaryText}.`].filter(Boolean),raw_payload:{dataset_resource_id:latest.id,dataset_resource_name:latest.name,wic_job_location_snapshot_id:id,job_title:title,original_job_title:get('Original Job Title'),noc21_code:noc,noc21_name:nocName,first_posting_date:first,vacancy_count:n(vac),official_language:official,education:edu,experience:exp,province:prov,city,employment_type:empType,employment_term:term,salary_per:salaryPer,salary_min:n(salaryMin),salary_max:n(salaryMax),annual_salary_low:a.lo,annual_salary_high:a.hi}});stored++;if(batch.length>=150){await upsertSignals(batch);batch=[]}}
while(true){const {value,done}=await reader.read();if(done)break;buffer+=dec.decode(value,{stream:true});let p;while((p=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,p);buffer=buffer.slice(p+1);await processLine(line)}if(stored>=4000){try{await reader.cancel()}catch{}break}}buffer+=dec.decode();if(buffer.trim()&&stored<4000)await processLine(buffer);if(batch.length)await upsertSignals(batch);await R(`world_sources?id=eq.${src.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_success_at:new Date().toISOString(),last_error:null,metadata:{...(src.metadata||{}),latest_resource_id:latest.id,latest_resource_name:latest.name,latest_resource_url:latest.url,latest_metadata_modified:meta?.result?.metadata_modified,pilot_scope:'Alberta rows from latest English monthly file',stored_cap:4000}})});return J({ok:true,source:'Canada Job Bank',resource:latest.name,scanned_rows:scanned,alberta_rows_seen:matched,stored_or_updated:stored,cap_reached:stored>=4000})}catch(e){if(src?.id)try{await R(`world_sources?id=eq.${src.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_error:String(e).slice(0,900)})})}catch{}return J({error:String(e)},500)}});