import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {runInNewContext} from "node:vm";
const src=readFileSync("supabase/functions/evidence-acquirer/evidence-core.js","utf8").replace(/export\s*\{[^}]*\};/g,"");
const acquire=runInNewContext(src+";acquireEvidence;");
const candidate={id:"c1",title:"Exterior renewal"};
const baseSignal={id:"s1",source_url:"https://purchasing.alberta.ca/posting/AB-2026-06600",organization:"Infrastructure",deadline_at:"2026-10-29T14:00:00Z",verified_facts:["Present in authoritative APC API."],raw_payload:{solicitationTypeCode:"RFP",opportunityTypeCode:"OPEN-COMPETITIVE",referenceNumber:"AB-2026-06600",solicitationNumber:"024300",bidSecurity:"Not Applicable",submissionDetails:"",additionalRequirements:null,projectDescription:"Lead paint and asbestos abatement, fiber cement cladding, and powered garage door electrical work."}};
const partial=acquire({candidate,signal:baseSignal,question:"Verify exact mandatory eligibility.",capabilities:[{name:"Siding and cladding"}],graphNodes:[]});
assert.equal(partial.conclusion.status,"partial");
assert.ok(partial.evidence.some(x=>x.field==="bid_security_published_field"&&x.value==="Not Applicable"));
assert.ok(partial.evidence.some(x=>x.field==="scope_dependencies"&&x.value.includes("hazardous_materials")));
assert.ok(partial.unresolved.some(x=>x.topic==="mandatory_eligibility"&&x.decision_sensitive));
assert.ok(partial.unresolved.some(x=>x.topic==="submission_method"&&x.decision_sensitive));
const corSignal={...baseSignal,raw_payload:{...baseSignal.raw_payload,submissionDetails:"Submit electronically.",additionalRequirements:"Prime contractor must provide a valid COR or SECOR before award."}};
const blocked=acquire({candidate,signal:corSignal,question:"Verify mandatory qualifications.",capabilities:[{name:"Siding and cladding"}],graphNodes:[]});
assert.equal(blocked.conclusion.status,"blocked_by_unverified_requirement");
assert.ok(blocked.unresolved.some(x=>x.topic==="COR_or_SECOR"));
const satisfied=acquire({candidate,signal:corSignal,question:"Verify mandatory qualifications.",capabilities:[{name:"Siding and cladding"}],graphNodes:[{node_type:"credential",label:"Valid SECOR",state:{status:"valid"}}]});
assert.equal(satisfied.conclusion.status,"complete");
assert.equal(satisfied.conclusion.decision_sensitive_gaps,0);
const economics=acquire({candidate,signal:{...baseSignal,raw_payload:{...baseSignal.raw_payload,submissionDetails:"Submit electronically.",additionalRequirements:"No additional published requirement."}},question:"Verify margin and project economics.",capabilities:[],graphNodes:[]});
assert.equal(economics.conclusion.status,"partial");
assert.ok(economics.unresolved.some(x=>x.topic==="project_economics"));
const fetchFail=acquire({candidate,signal:baseSignal,question:"Verify eligibility.",fetchSnapshot:{ok:false,error:"timeout"},capabilities:[],graphNodes:[]});
assert.ok(fetchFail.unresolved.some(x=>x.topic==="live_source_refresh"&&!x.decision_sensitive));
const docSideEffect=acquire({candidate,signal:baseSignal,question:"Retrieve the tender package.",capabilities:[],graphNodes:[],fetchSnapshot:{ok:true,status:200,final_url:baseSignal.source_url,content_type:"text/html",bytes:12000,sha256:"abc",fetched_at:"2026-10-01T00:00:00Z",text:"Document downloads Please take note When you download a document, you are automatically added to the Interested Suppliers List and subscribed to email notifications."}});
assert.equal(docSideEffect.conclusion.status,"approval_required_for_evidence");
assert.equal(docSideEffect.conclusion.approval_required_gaps,1);
assert.ok(docSideEffect.unresolved.some(x=>x.topic==="tender_document_access"&&x.requires_approval===true));
console.log("PASS evidence acquirer: authoritative facts, missing-doc uncertainty, credential gate, economics gap, fetch failure and side-effect approval");
