import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {runInNewContext} from "node:vm";
const src=readFileSync("supabase/functions/executive-council/deliberation-core.js","utf8").replace(/export\s*\{[^}]*\};/g,"");
const deliberate=runInNewContext(src+";deliberation;");
const candidate={id:"c1",title:"Exterior project"};
const baseCouncil={mode:"brief",chief_of_staff:{next_move:{approval_required:false},conflicts:[]},specialists:[{id:"business",status:"active",facts:[{text:"Capability overlap observed.",source:"capabilities"}]}]};
const learning={summary:{calibration_ready:0}};
const learn=deliberate({council:baseCouncil,candidate,personalValue:{not_known:["Exact eligibility is unverified."]},preparedWork:[{id:"w1",candidate_id:"c1",status:"prepared",content:{kind:"candidate_qualification",qualification_checks:[{label:"Eligibility",state:"needs_verification",detail:"Verify mandatory qualifications."}],unknowns:["Mandatory forms unknown."]}}],learningContext:learning});
assert.equal(learn.policy,"LEARN_FIRST");
assert.match(learn.highest_value_missing_fact,/Verify mandatory qualifications/);
assert.equal(learn.research_commission.auto_execution_authorized,true);
assert.equal(learn.research_commission.executor,"evidence-acquirer");
assert.match(learn.research_commission.boundary,/do not authenticate to external portals|do not.*contact anyone/i);
assert.equal(learn.competing_hypotheses.find(x=>x.id==="LEARN_FIRST").status,"leading");
const blocked=deliberate({council:{...baseCouncil,mode:"blocked",specialists:[{id:"finance",status:"blocked",challenge:"Capital requirement exceeds deployable cash.",facts:[]}]},candidate,preparedWork:[],learningContext:learning});
assert.equal(blocked.policy,"BLOCK");
assert.match(blocked.binding_constraint,/Capital requirement/);
const approval=deliberate({council:{...baseCouncil,chief_of_staff:{next_move:{approval_required:true},conflicts:[]}},candidate,personalValue:{not_known:[]},preparedWork:[],learningContext:learning});
assert.equal(approval.policy,"PREPARE_FOR_APPROVAL");
const proceed=deliberate({council:baseCouncil,candidate,personalValue:{not_known:[]},preparedWork:[],learningContext:{summary:{calibration_ready:2}}});
assert.equal(proceed.policy,"PROCEED_REVERSIBLY");
assert.match(proceed.calibration_note,/Historical calibration evidence/);
const quiet=deliberate({council:{mode:"quiet",chief_of_staff:{conflicts:[]},specialists:[]},candidate,personalValue:{not_known:["irrelevant"]},preparedWork:[],learningContext:learning});
assert.equal(quiet.policy,"QUIET");
assert.match(quiet.belief,/No personal intervention/);
const researchComplete=deliberate({council:baseCouncil,candidate,personalValue:{not_known:["Exact mandatory eligibility is unverified."]},preparedWork:[],researchArtifacts:[{id:"ra1",candidate_id:"c1",question:"Verify mandatory eligibility requirements.",status:"complete",evidence:[{field:"additional_requirements",value:"No additional published requirement."}],unresolved:[],conclusion:{status:"complete"}}],learningContext:learning});
assert.equal(researchComplete.policy,"PROCEED_REVERSIBLY");
assert.equal(researchComplete.research_status,"complete");
const researchPartial=deliberate({council:baseCouncil,candidate,personalValue:{not_known:["Exact eligibility is unverified."]},preparedWork:[],researchArtifacts:[{id:"ra2",candidate_id:"c1",question:"Verify mandatory eligibility requirements.",status:"partial",evidence:[{field:"bid_security_published_field",value:"Not Applicable"}],unresolved:[{topic:"mandatory_eligibility",reason:"Full mandatory tender-document requirements are not available.",decision_sensitive:true}],conclusion:{status:"partial"}}],learningContext:learning});
assert.equal(researchPartial.policy,"LEARN_FIRST");
assert.match(researchPartial.highest_value_missing_fact,/mandatory tender-document requirements/);
const researchBlocked=deliberate({council:baseCouncil,candidate,personalValue:{not_known:[]},preparedWork:[],researchArtifacts:[{id:"ra3",candidate_id:"c1",question:"Verify COR requirement.",status:"partial",evidence:[{field:"published_requirement_COR_or_SECOR",value:true}],unresolved:[{topic:"COR_or_SECOR",reason:"COR is published but not evidenced in the Twin.",decision_sensitive:true}],conclusion:{status:"blocked_by_unverified_requirement"}}],learningContext:learning});
assert.equal(researchBlocked.policy,"BLOCK");
assert.match(researchBlocked.binding_constraint,/COR/);
const researchApproval=deliberate({council:baseCouncil,candidate,personalValue:{not_known:["Tender package requirements are not verified."]},preparedWork:[],researchArtifacts:[{id:"ra4",candidate_id:"c1",question:"Retrieve tender package.",status:"partial",evidence:[{field:"public_document_section_detected",value:true}],unresolved:[{topic:"tender_document_access",reason:"Downloading registers supplier interest.",decision_sensitive:true,requires_approval:true}],conclusion:{status:"approval_required_for_evidence"}}],learningContext:learning});
assert.equal(researchApproval.policy,"LEARN_FIRST");
assert.equal(researchApproval.research_commission.auto_execution_authorized,false);
assert.equal(researchApproval.research_commission.approval_required,true);
assert.equal(researchApproval.research_commission.executor,null);
assert.match(researchApproval.research_commission.boundary,/external side effect/i);
console.log("PASS adversarial deliberation: quiet, learn-first, hard block, approval, reversible proceed, research resolution and evidence-side-effect approval");
