import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {runInNewContext} from "node:vm";
const src=readFileSync("supabase/functions/executive-council/deliberation-core.js","utf8").replace(/export\s*\{[^}]*\};/g,"");
const deliberate=runInNewContext(src+";deliberation;");
const candidate={id:"c1",title:"Exterior project"};
const baseCouncil={mode:"brief",chief_of_staff:{next_move:{approval_required:false},conflicts:[]},specialists:[{id:"business",status:"active",facts:[{text:"Capability overlap observed.",source:"capabilities"}]}]};
const learning={summary:{calibration_ready:0}};
const learn=deliberate({council:baseCouncil,candidate,personalValue:{not_known:["Exact eligibility is unverified."]},preparedWork:[{id:"w1",candidate_id:"c1",status:"prepared",content:{kind:"candidate_qualification",qualification_checks:[{label:"Eligibility",state:"needs_verification",detail:"Verify mandatory qualifications."}],unknowns:["Mandatory forms unknown."]}}],learningContext:learning});
assert.equal(learn.policy,"LEARN_FIRST");
assert.match(learn.highest_value_missing_fact,/Verify mandatory qualifications/);
assert.equal(learn.research_commission.auto_execution_authorized,false);
assert.equal(learn.competing_hypotheses.find(x=>x.id==="LEARN_FIRST").status,"leading");
const blocked=deliberate({council:{...baseCouncil,mode:"blocked",specialists:[{id:"finance",status:"blocked",challenge:"Capital requirement exceeds deployable cash.",facts:[]}]},candidate,preparedWork:[],learningContext:learning});
assert.equal(blocked.policy,"BLOCK");
assert.match(blocked.binding_constraint,/Capital requirement/);
const approval=deliberate({council:{...baseCouncil,chief_of_staff:{next_move:{approval_required:true},conflicts:[]}},candidate,personalValue:{not_known:[]},preparedWork:[],learningContext:learning});
assert.equal(approval.policy,"PREPARE_FOR_APPROVAL");
const proceed=deliberate({council:baseCouncil,candidate,personalValue:{not_known:[]},preparedWork:[],learningContext:{summary:{calibration_ready:2}}});
assert.equal(proceed.policy,"PROCEED_REVERSIBLY");
assert.match(proceed.calibration_note,/Historical calibration evidence/);
const quiet=deliberate({council:{mode:"quiet",chief_of_staff:{conflicts:[]},specialists:[]},candidate,personalValue:{not_known:["irrelevant"]},preparedWork:[],learningContext:learning});
assert.equal(quiet.policy,"QUIET");
assert.match(quiet.belief,/No personal intervention/);
console.log("PASS adversarial deliberation: quiet, learn-first, hard block, approval and reversible proceed");
