
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {runInNewContext} from "node:vm";
const source=readFileSync("supabase/functions/learning-context/learning-core.js","utf8").replace(/export\s*\{[^}]*\};/g,"");
const classify=runInNewContext(source+";classifyObservation;");
const reason={id:"r1"},exec={id:"d1",action:"execute",reasoning_run_id:"r1"},investigate={id:"d2",action:"investigate",reasoning_run_id:"r1"};
assert.equal(classify({facts:{stage:"quoted"}},null,null,25).state,"observed_unlinked");
assert.equal(classify({facts:{stage:"quoted"}},{id:"d",action:"execute",reasoning_run_id:"missing"},null,25).state,"decision_without_prediction_trace");
assert.equal(classify({facts:{stage:"won"}},investigate,reason,25).state,"pre_execution_observation");
const won=classify({facts:{stage:"won",contract_value:100000}},exec,reason,25);
assert.equal(won.state,"won_profit_unverified");
assert.equal(won.calibration_ready,false);
assert.equal(won.goal_qualification,null);
const good=classify({facts:{stage:"completed",actual_margin_pct:31,actual_gross_profit:31000}},exec,reason,25);
assert.equal(good.state,"calibration_ready");
assert.equal(good.calibration_ready,true);
assert.equal(good.goal_qualification,true);
const thin=classify({facts:{stage:"completed",actual_margin_pct:18,actual_gross_profit:18000}},exec,reason,25);
assert.equal(thin.calibration_ready,true);
assert.equal(thin.goal_qualification,false);
const lost=classify({facts:{stage:"lost",loss_reason:"price"}},exec,reason,25);
assert.equal(lost.state,"calibration_candidate");
assert.equal(lost.calibration_ready,true);
assert.equal(lost.goal_qualification,false);
const waiting=classify({facts:{stage:"active"}},exec,reason,25);
assert.equal(waiting.state,"outcome_incomplete");
assert.equal(waiting.calibration_ready,false);
console.log("PASS learning context: unlinked, missing trace, pre-execution, won/unverified, completed margin, loss and incomplete outcome");
