import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
const graph=readFileSync("supabase/functions/personal-graph-core/index.ts","utf8");
const trajectory=readFileSync("supabase/functions/trajectory-context/index.ts","utf8");
const twin=readFileSync("pios/life-twin-ui.js","utf8");
for(const node of ["commitment","operating_record","decision","prepared_work","outcome_observation","source_connection"]) assert.ok(graph.includes("'"+node+"'"),"canonical graph missing node type "+node);
for(const relation of ["has_goal","has_commitment","tracks_operating_record","acts_on","prepares_for","observes","evidence_source_for"]) assert.ok(graph.includes("'"+relation+"'"),"canonical graph missing relationship "+relation);
assert.ok(graph.includes("seenRefs=new Set"),"sync must track currently observed source refs");
assert.ok(graph.includes("valid_to:closedAt"),"stale graph nodes must be closed temporally, not deleted");
assert.ok(graph.includes("personal_graph_edges?user_id=eq.")&&graph.includes("valid_to=is.null"),"stale-node edges must also be closed");
assert.ok(graph.includes("personal_graph_core_v3_temporal_life_state"),"graph contract version must identify temporal state");
assert.ok(trajectory.includes("life_graph:graphSummary")&&trajectory.includes("graph:graphSummary"),"Digital Twin context must expose canonical graph summary");
assert.ok(trajectory.includes("personal_graph_nodes?user_id=eq.")&&trajectory.includes("valid_to=is.null"),"Digital Twin must read only active graph nodes");
assert.ok(!twin.includes("CORE MODEL"),"live Twin must not expose engineering completeness telemetry");
assert.ok(twin.includes("LIVE PERSONAL MODEL"),"live Twin must present personal state rather than model score");
console.log("PASS canonical life graph: whole-person nodes, explicit relationships, temporal closure and Twin integration");
