
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
const page=readFileSync("pios/index.html","utf8");
const presence=readFileSync("pios/presence-ui.js","utf8");
const style=readFileSync("pios/command-navigation.css","utf8");
const twin=readFileSync("pios/life-twin-ui.js","utf8");
const orch=readFileSync("supabase/functions/universal-orchestrate/index.ts","utf8");
const workbench=readFileSync("supabase/functions/executive-workbench/index.ts","utf8");
for(const src of ["presence-ui.js","presence-ui.css"])assert.ok(page.includes(src),"presence asset must be included in production");
for(const id of ["globeWrap","globe","authBtn","refreshBtn","settingsBtn"])assert.ok(page.includes('id="'+id+'"'),"original core control missing: "+id);
for(const id of ["presenceNeed","presencePrepared","presenceQuiet","presenceChecked"])
 assert.ok(presence.includes('id="'+id+'"'),"home presence section missing: "+id);
assert.ok(style.includes('body[data-pios-view="command"] .right-rail{display:none}'),"dashboard should not overpower home");
assert.ok(style.includes('body[data-pios-view="command"] .left-rail{display:none!important}'),"Command Center must not expose the profile dashboard");
assert.ok(style.includes('grid-template-columns:minmax(0,1fr)'),"Command Center must give the Earth/presence the full width");
assert.ok(twin.includes("window.updatePiosPresence"),"twin updates must feed the executive presence");
assert.ok(orch.includes("callFn('executive-workbench'"),"the intelligence cycle must perform bounded internal preparation");
assert.ok(workbench.includes('operation!=="prepare_quote"'),"workbench must reject unsupported operations");
assert.ok(workbench.includes('stage=eq.quoted'),"only owned quoted work may be prepared");
assert.ok(workbench.includes("external_action_performed:false"),"preparation must never claim external action");
assert.ok(presence.includes("w?.is_current"),"stale prepared artifacts cannot be marked current");
assert.ok(presence.includes("external_message_sent"),"draft state must keep external contact distinguishable");
assert.ok(presence.includes("Prepare quotation follow-up"),"a relevant person can trigger internal preparation directly");
assert.ok(presence.includes("result?.prepared&&currentWork()"),"the interface cannot claim completed work until it reloads the stored artifact");
assert.ok(presence.includes("autoPreparedForToken!==token"),"safe preparation should run at most once per connected session");
assert.ok(presence.includes("prep?.prepared&&localStorage.getItem('pios_token')===token"),"auto preparation may display results only for the same session");
assert.ok(presence.includes("does not establish a continuous watch"),"no unconfigured always-on monitoring claims");
assert.ok(presence.includes("strategyMove?.candidate_id"),"recorded strategies must remain visible even if the Council is unavailable");
assert.ok(presence.includes("candidate_id:strategyMove.candidate_id"),"internal preparation must follow the selected owned opportunity");
assert.ok(presence.includes("workError?'Prepared work is temporarily unavailable.'"),"failed preparation reads must not imply no work exists");
const life=readFileSync("pios/life-twin-ui.js","utf8");
assert.ok(life.includes("const critical=[")&&life.includes("const supplemental=["),"essential decisions must load ahead of simulations");
assert.ok(life.includes("Promise.race"),"optional slow endpoints must not stall the executive brief");
const nav=readFileSync("pios/command-navigation.css","utf8");
assert.ok(nav.includes(".world-stage.world-mode{display:flex"),"world Earth must not inherit the phantom grid row");
assert.ok(nav.includes(".world-stage.twin-mode>.presence-deck{grid-row:2"),"the executive decision must be visible on arrival");
const truth=readFileSync("pios/model-truth-ui.js","utf8");
assert.ok(truth.includes("modelTruthDiagnostics")&&!truth.includes("detail.innerHTML="),"coverage diagnostics must not overwrite selected decisions");
console.log("PASS ambient executive presence: core Earth/Connect preserved, honest work status, guarded preparation and focused home");

const app=readFileSync("pios/app.js","utf8");
assert.ok(app.includes("pios_auto_review_done"),"connected sessions should trigger one automatic personal review");
assert.ok(app.includes("REVIEWING PERSONAL STATE"),"automatic review state should be visible without implying continuous monitoring");
assert.ok(page.includes(">Recheck now<"),"manual refresh is secondary, not the primary operating model");
