import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")!,A=Deno.env.get("SUPABASE_ANON_KEY")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...C,"Content-Type":"application/json","Cache-Control":"no-store"}});
async function getUser(jwt:string){const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:A,Authorization:`Bearer ${jwt}`}});if(!r.ok)return null;return r.json()}async function R(path:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set('apikey',K);h.set('Authorization',`Bearer ${K}`);if(init.body)h.set('Content-Type','application/json');let r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:h}),t=await r.text();if(!r.ok&&r.status===401&&t.includes('JWT issued at future')){await new Promise(x=>setTimeout(x,800));r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:h});t=await r.text()}if(!r.ok)throw Error(`${r.status} ${t.slice(0,500)}`);return t?JSON.parse(t):null}
async function learn(uid:string,dimension:string,key:string,delta:number){if(!key||!Number.isFinite(delta)||delta===0)return null;const cur=(await R(`learning_weights?user_id=eq.${uid}&dimension=eq.${encodeURIComponent(dimension)}&key=eq.${encodeURIComponent(key)}&select=*`))?.[0];const next=Math.max(.5,Math.min(1.5,Number(cur?.weight||1)+delta)),count=Number(cur?.evidence_count||0)+1,row={user_id:uid,dimension,key,weight:Number(next.toFixed(3)),evidence_count:count,updated_at:new Date().toISOString()};return(await R('learning_weights?on_conflict=user_id,dimension,key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify([row])}))?.[0]||row}
function scopeKeys(s:any){if(Array.isArray(s))return s.map(String);if(s&&typeof s==='object'){const a=s.matches||s.matched_terms||[];return Array.isArray(a)?a.map(String):[]}return[]}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'POST required'},405);const jwt=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!jwt)return J({error:'Missing bearer token'},401);const u=await getUser(jwt);if(!u?.id)return J({error:'Invalid user'},401);try{const b=await req.json(),candidateId=String(b.candidate_id||''),action=String(b.action||''),allowed=['investigate','watch','reject','approve','execute','ignore'];if(!candidateId||!allowed.includes(action))return J({error:'candidate_id and valid action required'},400);const cand=(await R(`opportunity_candidates?id=eq.${candidateId}&user_id=eq.${u.id}&select=*`))?.[0];if(!cand)return J({error:'Candidate not found or not owned by user'},404);const recentReasoning=await R(`reasoning_runs?user_id=eq.${u.id}&select=*&order=generated_at.desc&limit=20`);const reasoningRun=(recentReasoning||[]).find((x:any)=>String(x?.recommendation?.candidate_id||'')===candidateId)||null;let recommendationId=b.recommendation_id||null;if(recommendationId){const rec=(await R(`recommendations?id=eq.${recommendationId}&user_id=eq.${u.id}&select=id`))?.[0];if(!rec)return J({error:'Recommendation not found or not owned by user'},404)}const dec=(await R('decisions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{user_id:u.id,candidate_id:candidateId,recommendation_id:recommendationId,reasoning_run_id:reasoningRun?.id||null,action,rationale:b.rationale||null}])}))?.[0];const statusMap:any={investigate:'investigate',watch:'watch',reject:'rejected',ignore:'rejected',approve:'approved',execute:'executing'};await R(`opportunity_candidates?id=eq.${candidateId}&user_id=eq.${u.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:statusMap[action],updated_at:new Date().toISOString()})});
const typeKey=String(cand.opportunity_type||cand.category||'unknown'),moduleKey=String(cand.module_code||'unclassified'),decisionDelta:any={investigate:.025,watch:.01,approve:.04,execute:.05,reject:-.035,ignore:-.025},base=decisionDelta[action]||0,learned:any[]=[];for(const [dim,key,delta] of [['opportunity_type',typeKey,base],['module_preference',moduleKey,base*.55]] as any[]){const w=await learn(u.id,dim,key,delta);if(w)learned.push(w)}for(const k of scopeKeys(cand.scope_match).slice(0,4)){const w=await learn(u.id,'scope_preference',String(k),Math.sign(base)*.01);if(w)learned.push(w)}
let outcome=null;if(b.outcome){const o=b.outcome,allowedStatus=['pending','positive','neutral','negative','unknown'],st=allowedStatus.includes(String(o.status))?String(o.status):'pending';outcome=(await R('outcomes',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{user_id:u.id,decision_id:dec.id,status:st,observed_at:o.observed_at||new Date().toISOString(),monetary_impact:o.monetary_impact==null?null:Number(o.monetary_impact),time_impact_hours:o.time_impact_hours==null?null:Number(o.time_impact_hours),metric_delta:o.metric_delta||{},notes:o.notes||null}])}))?.[0];const od:any={positive:.12,neutral:0,negative:-.15,unknown:0,pending:0};let d=od[st]||0,mi=Number(o.monetary_impact||0);if(st==='positive'&&mi>0)d+=Math.min(.08,Math.log10(mi+1)/100);if(st==='negative'&&mi<0)d-=Math.min(.08,Math.log10(Math.abs(mi)+1)/100);for(const [dim,key,delta] of [['opportunity_type',typeKey,d],['module_preference',moduleKey,d*.65]] as any[]){const w=await learn(u.id,dim,key,delta);if(w)learned.push(w)}for(const k of scopeKeys(cand.scope_match).slice(0,4)){const w=await learn(u.id,'scope_preference',String(k),Math.sign(d)*Math.min(.04,Math.abs(d)*.3));if(w)learned.push(w)}
if(reasoningRun&&outcome){
  const rr=reasoningRun.recommendation||{},sp=rr.success_probability==null?null:Number(rr.success_probability),actual=st==='positive'?1:st==='negative'?0:null,brier=sp!=null&&actual!=null?Math.pow(sp/100-actual,2):null;
  let errorClass='calibration_observation';const lessons:any[]=[];
  if(actual===0&&sp!=null&&sp>=60){errorClass='prediction_miss';lessons.push('Outcome contradicted a materially positive success estimate; inspect assumptions, evidence quality and execution.')}
  else if(actual===1&&sp!=null&&sp<=40){errorClass='positive_surprise';lessons.push('Outcome materially outperformed the prior success estimate; inspect which evidence or capability was undervalued.')}
  if(st==='negative'&&(reasoningRun.metadata?.what_would_change_mind||[]).length)lessons.push('Compare the failed outcome with the prior mind-change conditions and mark which condition was triggered.');
  await R('reasoning_outcome_reviews',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{user_id:u.id,reasoning_run_id:reasoningRun.id,decision_id:dec.id,outcome_id:outcome.id,predicted_decision:rr.decision||null,predicted_confidence:rr.confidence??null,predicted_success_probability:sp,predicted_expected_value:rr.expected_value??null,predicted_currency:rr.expected_value_currency||null,actual_status:st,actual_monetary_impact:o.monetary_impact==null?null:Number(o.monetary_impact),brier_error:brier,error_class:errorClass,lessons}])});
}}return J({ok:true,decision:dec,outcome,reasoning_run_id:reasoningRun?.id||null,learning_updates:learned,note:'Decisions retain reasoning provenance. Verified outcomes update bounded preferences and, when possible, create a calibration review against the prediction that produced the decision.'})}catch(e){return J({error:String(e)},500)}});