import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const CSV="https://www.calgary.ca/content/dam/www/ca/fs/documents/bid-and-vendor-information/prequalified-prime-contractors.csv";
const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Cache-Control":"no-store"}});
async function F(path:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set("apikey",K);h.set("Authorization",`Bearer ${K}`);if(init.body)h.set("Content-Type","application/json");let r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:h});let t=await r.text();if(!r.ok&&r.status===401&&t.includes("JWT issued at future")){await new Promise(x=>setTimeout(x,850));r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:h});t=await r.text()}if(!r.ok)throw Error(`${r.status} ${t.slice(0,400)}`);return t?JSON.parse(t):null}
function parse(text:string){const out:string[][]=[];let row:string[]=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))out.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}return out}
const clean=(s:any)=>String(s??"").replace(/&amp;/g,"&").replace(/<br\s*\/?>/gi,"\n").replace(/\\n/g,"\n").trim();

async function piosCronSecret(){const r=await fetch(`${U}/rest/v1/system_secrets?name=eq.scheduled_intelligence&select=secret`,{headers:{apikey:K,Authorization:`Bearer ${K}`}});if(!r.ok)return "";const a=await r.json();return a?.[0]?.secret||""}
function piosSafe(a:string,b:string){if(!a||!b||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function piosAuthorized(req:Request){return piosSafe(req.headers.get("x-pios-cron-token")||"",await piosCronSecret())}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return J({error:"POST required"},405);if(!(await piosAuthorized(req)))return J({error:"unauthorized"},401);let src:any=null;try{src=(await F("world_sources?code=eq.calgary_prequalified_primes&select=id,last_success_at"))?.[0];if(src?.last_success_at&&Date.now()-new Date(src.last_success_at).getTime()<8*3600000)return J({ok:true,skipped:true,last_success_at:src.last_success_at});const r=await fetch(CSV,{headers:{"User-Agent":"Personal-Intelligence-OS/1.0"}});if(!r.ok)throw Error(`City Calgary prime list ${r.status}`);const rows=parse(await r.text());if(rows.length<2)throw Error("Prime contractor CSV empty");const H=rows[0].map(x=>x.replace(/^\uFEFF/,"").trim());const low=H.map(x=>x.toLowerCase());let categoryIdx=low.findIndex(x=>x.includes("technical category")||x.includes("category"));let contractorsIdx=low.findIndex(x=>x.includes("approved prequalified prime contractors")||x.includes("contractor"));if(categoryIdx<0||contractorsIdx<0)throw Error(`Unrecognized headers: ${H.join(" | ")}`);const records:any[]=[];for(const rr of rows.slice(1)){const category=clean(rr[categoryIdx]);const block=clean(rr[contractorsIdx]);if(!category||!block)continue;const companies=block.split(/\n+/).map(x=>x.trim()).filter(Boolean);for(const company of companies)records.push({source_code:"calgary_prequalified_primes",company_name:company,category,valid_as_of:"2026-08-19",source_url:"https://www.calgary.ca/buy-sell/supply-to-city/prime-contractors.html",raw_payload:Object.fromEntries(H.map((h,i)=>[h,rr[i]??""])),updated_at:new Date().toISOString()})}for(let i=0;i<records.length;i+=150){await F("prime_contractor_directory?on_conflict=source_code,company_name,category",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(records.slice(i,i+150))})}if(src?.id)await F(`world_sources?id=eq.${src.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({last_success_at:new Date().toISOString(),last_error:null,metadata:{purpose:"subcontract partner and prime contractor intelligence",records:records.length,headers:H}})});return J({ok:true,headers:H,records:records.length,unique_companies:[...new Set(records.map(x=>x.company_name))].length,sample:records.slice(0,8).map(x=>({company:x.company_name,category:x.category}))})}catch(e){try{if(src?.id)await F(`world_sources?id=eq.${src.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({last_error:String(e).slice(0,500)})})}catch{}return J({error:String(e)},500)}});