import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get('SUPABASE_URL')!,A=Deno.env.get('SUPABASE_ANON_KEY')!;
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,x-client-info,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
async function authUser(jwt:string){try{const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:A,Authorization:`Bearer ${jwt}`}});if(!r.ok)return null;return await r.json()}catch{return null}}
async function rest(path:string,jwt:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set('apikey',A);h.set('Authorization',`Bearer ${jwt}`);if(init.body)h.set('Content-Type','application/json');let r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:h}),t=await r.text();if(!r.ok&&r.status===401&&t.includes('JWT issued at future')){await new Promise(x=>setTimeout(x,850));r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:h});t=await r.text()}if(!r.ok)throw Error(`${path} ${r.status}: ${t.slice(0,600)}`);return t?JSON.parse(t):null}
async function callFn(slug:string,jwt:string,body:any={},timeout=90000){const started=Date.now();const r=await fetch(`${U}/functions/v1/${slug}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:A,Authorization:`Bearer ${jwt}`},body:JSON.stringify(body),signal:AbortSignal.timeout(timeout)});const t=await r.text();let data:any=null;try{data=t?JSON.parse(t):null}catch{data={raw:t.slice(0,1200)}}if(!r.ok)throw Error(`${slug} ${r.status}: ${t.slice(0,700)}`);return{data,elapsed_ms:Date.now()-started}}
function moduleSummary(code:string,x:any,elapsed_ms:number){const d=x||{},ops=Array.isArray(d.opportunities)?d.opportunities:Array.isArray(d?.refined?.surfaced)?d.refined.surfaced:[];return{module_code:code,ok:true,elapsed_ms,scanner_run_id:d.scanner_run_id||null,surfaced:ops.length||d?.persisted?.length||d?.stats?.surfaced||0,next_best:d.nextBest?{title:d.nextBest.title||null,score:d.nextBest.score??null,decision:d.nextBest.decision||d.nextBest.opportunity_type||null,next_action:d.nextBest.next_action||null}:d?.refined?.nextBest||null,stats:d.stats||d?.initialScan?.stats||null}}
function buildSequence(strat:any){if(strat?.sequence?.steps?.length)return strat.sequence;const next=strat?.next_best_move||{},portfolio=(Array.isArray(strat?.portfolio)?strat.portfolio:[]).slice().sort((a:any,b:any)=>Number(b.score||0)-Number(a.score||0));if(!next?.candidate_id||next?.score==null)return strat?.sequence||null;const alt=portfolio.find((x:any)=>x.id!==next.candidate_id&&Number(next.score)-Number(x.score||0)<=5&&Number(x.score||0)>=70);if(!alt)return null;const gap=Number((Number(next.score)-Number(alt.score||0)).toFixed(1));return{steps:[{order:1,label:'NOW',candidate_id:next.candidate_id,module_code:next.module_code,title:next.title,action:next.action,why:'Highest current strategy score; handle the time-sensitive or immediately actionable move first.'},{order:2,label:'NEXT',candidate_id:alt.id,module_code:alt.module_code,title:alt.title,action:alt.next_action||'Investigate the near-tied alternative after the current move is qualified.',why:'Near-tied strategy option retained so the broader goal does not disappear behind one opportunity.'}],reason:`The top move leads the next alternative by only ${gap} points. Execute or qualify NOW, then preserve the near-tied NEXT move.`}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'POST required'},405);const jwt=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!jwt)return J({error:'Missing bearer token'},401);const user=await authUser(jwt);if(!user?.id)return J({error:'Invalid user'},401);const started=Date.now();try{
let goalContract:any=null;try{const g=await callFn('goal-contract',jwt,{},30000);goalContract={ok:true,contract:g.data?.contract||null,generated:g.data?.generated||false,parsed_metrics:g.data?.parsed_metrics||null}}catch(e){goalContract={ok:false,error:String(e).slice(0,500)}}
const routed=await callFn('intelligence-router',jwt,{},30000),router=routed.data||{};if(router.needs_onboarding)return J(router,409);const active=new Set((router.active||[]).map((x:any)=>String(x.code)));const runners=[{code:'construction',slug:'world-scan',timeout:100000},{code:'career_income',slug:'career-scan',timeout:70000},{code:'grants_funding',slug:'funding-scan',timeout:120000},{code:'education_skills',slug:'skills-scan',timeout:70000}],selected=runners.filter(x=>active.has(x.code));const results=await Promise.all(selected.map(async m=>{try{const r=await callFn(m.slug,jwt,{},m.timeout);return moduleSummary(m.code,r.data,r.elapsed_ms)}catch(e){return{module_code:m.code,ok:false,error:String(e).slice(0,900)}}}));
let synthesis:any=null;try{const s=await callFn('portfolio-synthesis',jwt,{},60000);synthesis={ok:true,elapsed_ms:s.elapsed_ms,candidate_count:s.data?.candidate_count||0,links_generated:s.data?.links_generated||0,sequences:(s.data?.sequences||[]).slice(0,5)}}catch(e){synthesis={ok:false,error:String(e).slice(0,900)}}
let operatingMemory:any=null;if(active.has('business_growth')){try{const o=await callFn('operating-strategy-sync',jwt,{},30000);operatingMemory={ok:true,elapsed_ms:o.elapsed_ms,diagnostic:o.data?.diagnostic||null,candidate_id:o.data?.candidate?.id||null,operating_records:o.data?.operating_records||0}}catch(e){operatingMemory={ok:false,error:String(e).slice(0,700)}}}
let personalGraph:any=null;try{const g=await callFn('personal-graph-sync',jwt,{},60000);personalGraph={ok:true,elapsed_ms:g.elapsed_ms,nodes_synced:g.data?.nodes_synced||0,edges_synced:g.data?.edges_synced||0,recent_changes:g.data?.recent_changes||[]}}catch(e){personalGraph={ok:false,error:String(e).slice(0,900)}}
let strategy:any=null;try{const s=await callFn('strategy-brief',jwt,{},60000);strategy={ok:true,elapsed_ms:s.elapsed_ms,...s.data};if(strategy?.strategy)strategy.strategy.sequence=buildSequence(strategy.strategy)}catch(e){strategy={ok:false,error:String(e).slice(0,900)}}
let simulation:any=null;if(strategy?.ok&&strategy?.strategy){try{const sim=await callFn('future-simulator',jwt,{persist:true},30000);simulation={ok:true,elapsed_ms:sim.elapsed_ms,...sim.data}}catch(e){simulation={ok:false,error:String(e).slice(0,700)}}}
let actionPlan:any=null;if(strategy?.ok&&strategy?.strategy){try{const ap=await callFn('action-graph',jwt,{persist:true},30000);actionPlan={ok:true,elapsed_ms:ap.elapsed_ms,...ap.data}}catch(e){actionPlan={ok:false,error:String(e).slice(0,700)}}}
let preparedWork:any=null;
try{
  const wp=await callFn('executive-workbench',jwt,{operation:'prepare_quote'},30000);
  preparedWork={ok:true,elapsed_ms:wp.elapsed_ms,prepared:wp.data?.prepared===true,
    already_prepared:wp.data?.already_prepared===true,work_id:wp.data?.work?.id||null,
    operating_id:wp.data?.work?.operating_id||null,reason:wp.data?.reason||null};
}catch(e){preparedWork={ok:false,error:String(e).slice(0,420)}}
let preparedWork:any=null;try{const z=await callFn('executive-workbench',jwt,{operation:'prepare_quote'},30000);preparedWork={ok:true,prepared:z.data?.prepared===true,work_id:z.data?.work?.id||null,reason:z.data?.reason||null};}catch(e){preparedWork={ok:false,error:String(e).slice(0,300)}}
let snapshot:any=null;if(strategy?.ok&&strategy?.strategy){try{const row={user_id:user.id,generated_at:new Date().toISOString(),orchestration_version:'decision_engine_v10_counterfactual_simulation+universal_orchestrator_v8_action_graph',next_best_move:strategy.strategy.next_best_move||null,sequence:strategy.strategy.sequence||null,attention_shield:strategy.strategy.attention_shield||null,horizons:strategy.strategy.horizons||null,portfolio:strategy.strategy.portfolio||null,graph:{...strategy.graph,personal_graph:personalGraph},self_model:strategy.self_model||null,learning:strategy.learning||null,module_state:{source:'universal-orchestrator-v8-action-graph',active_modules:(router.active||[]).map((x:any)=>({code:x.code,name:x.name,relevance_score:x.relevance_score})),module_results:results.map((x:any)=>({module_code:x.module_code,ok:x.ok,surfaced:x.surfaced||0,error:x.error||null})),goal_contract:goalContract,operating_memory:operatingMemory,simulation:simulation?.ok?{engine_version:simulation.engine_version||null,simulation_run_id:simulation.simulation_run_id||null,preferred_scenario:simulation.preferred_scenario||null,uncertainty:simulation.uncertainty||null}:simulation,internal_preparation:preparedWork,internal_preparation:preparedWork,action_graph:actionPlan?.ok?{plan_id:actionPlan.plan?.id||null,pathway:actionPlan.plan?.pathway||null,objective:actionPlan.plan?.objective||null,steps:(actionPlan.plan?.steps||[]).map((x:any)=>({id:x.id,label:x.label,auto_allowed:x.auto_allowed,approval_required:x.approval_required,status:x.status}))}:actionPlan,decision_engine:{version:'decision_engine_v10_counterfactual_simulation',principle:'WORLD_TO_YOU + YOU_TO_WORLD + UNKNOWN_TO_LEARN, governed by hypothesis testing, counterfactual comparison, contradiction checks, uncertainty, future-state simulation and explicit mind-change conditions.'}}};snapshot=(await rest('strategy_snapshots',jwt,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([row])}))?.[0]||null}catch(e){snapshot={error:String(e).slice(0,700)}}}
const succeeded=results.filter((x:any)=>x.ok).length,failed=results.filter((x:any)=>!x.ok).length;return J({ok:failed===0&&strategy?.ok!==false,orchestration_version:'decision_engine_v10_counterfactual_simulation+universal_orchestrator_v8_action_graph',generated_at:new Date().toISOString(),user_id:user.id,elapsed_ms:Date.now()-started,goal_contract:goalContract,router:{version:router.router_version||null,active:(router.active||[]).map((x:any)=>({code:x.code,name:x.name,relevance_score:x.relevance_score,reason:x.reason})),watch:(router.watch||[]).map((x:any)=>({code:x.code,name:x.name,relevance_score:x.relevance_score})),elapsed_ms:routed.elapsed_ms},modules:{requested:selected.length,succeeded,failed,results},synthesis,operating_memory:operatingMemory,personal_graph:personalGraph,strategy,simulation,action_graph:actionPlan,internal_preparation:preparedWork,snapshot:snapshot?{id:snapshot.id||null,generated_at:snapshot.generated_at||null,error:snapshot.error||null}:null,principle:'One run updates the goal and world model, synchronizes operating evidence, rebuilds the Personal Graph, routes candidate options through cognition and meta-reasoning, simulates alternative future Twin states, builds a guarded action graph, then saves one strategy with human approval preserved for consequential actions.'})}catch(e){return J({error:String(e),orchestration_version:'decision_engine_v10_counterfactual_simulation+universal_orchestrator_v8_action_graph'},500)}});