import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")!,A=Deno.env.get("SUPABASE_ANON_KEY")!;
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...C,"Content-Type":"application/json","Cache-Control":"no-store"}});
const clamp=(n:any)=>Math.max(0,Math.min(100,Math.round(Number(n)||0)));
async function F(url:string,init:RequestInit={}){let r=await fetch(url,init),t=await r.text();if(!r.ok&&r.status===401&&t.includes('JWT issued at future')){await new Promise(x=>setTimeout(x,800));r=await fetch(url,init);t=await r.text()}if(!r.ok)throw Error(`${r.status} ${t.slice(0,650)}`);return t?JSON.parse(t):null}
async function authUser(jwt:string){try{return await F(`${U}/auth/v1/user`,{headers:{apikey:A,Authorization:`Bearer ${jwt}`}})}catch{return null}}
async function R(path:string,jwt:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set('apikey',A);h.set('Authorization',`Bearer ${jwt}`);if(init.body)h.set('Content-Type','application/json');return F(`${U}/rest/v1/${path}`,{...init,headers:h})}
async function callCareer(profile:any,jwt:string){return F(`${U}/functions/v1/career-evaluate`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${jwt}`},body:JSON.stringify({profile}),signal:AbortSignal.timeout(20000)})}
async function ins(table:string,jwt:string,row:any){return (await R(table,jwt,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([row])}))?.[0]}
async function patch(path:string,jwt:string,row:any){return (await R(path,jwt,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))?.[0]}
function goalText(g:any[]){const x=g?.[0]||{};return String(x.title||x.description||'Improve my economic position')}
function capText(c:any[]){return(c||[]).map(x=>[x.name,x.category,x.evidence].filter(Boolean).join(' — ')).join('; ')}
function focusText(f:any[]){return(f||[]).filter(x=>x.active!==false).map(x=>x.name).join('; ')}
function resourceText(r:any[]){return(r||[]).filter(x=>x.active!==false).map(x=>[x.name,x.category,x.description].filter(Boolean).join(' — ')).join('; ')}
function statusFor(score:number){return score>=75?'investigate':score>=55?'watch':'watch'}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'POST required'},405);const jwt=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!jwt)return J({error:'Missing bearer token'},401);const user=await authUser(jwt);if(!user?.id)return J({error:'Invalid user'},401);let run:any=null;try{const[p,g,c,fa,ra,act]=await Promise.all([
R(`profiles?user_id=eq.${user.id}&select=*`,jwt),
R(`goals?user_id=eq.${user.id}&status=eq.active&select=*&order=priority.asc`,jwt),
R(`capabilities?user_id=eq.${user.id}&active=eq.true&select=*&order=proficiency.desc.nullslast`,jwt),
R(`focus_areas?user_id=eq.${user.id}&active=eq.true&select=*`,jwt),
R(`resources_assets?user_id=eq.${user.id}&active=eq.true&select=*`,jwt),
R(`user_module_activations?user_id=eq.${user.id}&module_code=eq.career_income&select=*`,jwt)
]);const profileRow=p?.[0];if(!profileRow)return J({needs_onboarding:true,message:'Create the Personal Model before running Career & Income Intelligence.'},409);const activation=act?.[0];if(!activation||activation.status!=='active')return J({module_inactive:true,module_code:'career_income',message:'Career & Income Intelligence is not active for this Personal Model. Run the Intelligence Router or activate the module manually.'},409);
const profile={goal:goalText(g||[]),location:profileRow.home_region||'',capabilities:capText(c||[]),focusAreas:focusText(fa||[]),resources:resourceText(ra||[]),risk:profileRow.risk_posture||'balanced',attentionMinutes:Number(profileRow.attention_budget_minutes||30)};
run=await ins('scanner_runs',jwt,{user_id:user.id,trigger_type:'manual',status:'running',metadata:{engine:'module:career-v1',module_code:'career_income',requested_at:new Date().toISOString()}});
const result=await callCareer(profile,jwt);const opportunities=Array.isArray(result?.opportunities)?result.opportunities:[];const persisted=[];
for(const o of opportunities.slice(0,5)){
  const existing=(await R(`opportunity_candidates?user_id=eq.${user.id}&module_code=eq.career_income&title=eq.${encodeURIComponent(o.title)}&status=in.(new,investigate,watch,approved,executing)&select=*&order=updated_at.desc&limit=1`,jwt))?.[0];
  const salary=o.salary||{},demand=o.demand||{};const assumptions=[...(o.unknowns||[]),'Job Bank monthly open data is evidence of recent market demand, not confirmation that a specific posting is still open.'];
  const row={scanner_run_id:run.id,module_code:'career_income',title:o.title,category:'career_income',status:statusFor(Number(o.score||0)),opportunity_type:'income_opportunity',eligibility_status:'unknown',eligibility_reason:'Role-level eligibility depends on employer requirements, credentials and work authorization; verify before applying.',horizon:o.horizon||'today',is_material:Boolean(o.material),primary_signal_id:null,scope_match:{matched_terms:o.match?.terms||[],exact_phrases:o.match?.exact_phrases||[],demand:o.demand||{},salary:o.salary||{}},relevance_score:clamp(o.relevance),confidence_score:clamp(o.confidence),impact_score:clamp(o.impact),executability_score:clamp(o.score>=80?82:o.score>=65?70:58),timing_score:clamp(o.timing),strategic_fit_score:clamp(Math.round((Number(o.relevance||0)*.75)+(Number(o.score||0)*.25))),risk_score:clamp(o.risk),capital_burden_score:clamp(o.capitalBurden),attention_cost_score:clamp(o.attentionCost),total_score:clamp(o.score),why_you:o.why_you||'Career opportunity matched the Personal Model.',mechanism:'A labor-market opportunity may improve income or career trajectory if the role, compensation and qualification requirements outperform the current path.',expected_upside_low:salary.observed_low??null,expected_upside_high:salary.observed_high??null,expected_downside_low:null,expected_downside_high:null,capital_required_low:0,capital_required_high:null,time_required_hours:null,currency:'CAD',window_end:null,next_action:o.next_action||'Verify active openings, qualifications and compensation before applying.',assumptions};
  let candidate:any,isNew=false;if(existing)candidate=await patch(`opportunity_candidates?id=eq.${existing.id}`,jwt,row);else{candidate=await ins('opportunity_candidates',jwt,{user_id:user.id,...row});isNew=true}
  if(!candidate)continue;
  if(isNew){for(const fact of(o.facts||[]).slice(0,8))await ins('opportunity_evidence',jwt,{user_id:user.id,candidate_id:candidate.id,signal_id:null,evidence_type:'fact',statement:String(fact),confidence:96,source_url:o.source_url||null});await ins('opportunity_evidence',jwt,{user_id:user.id,candidate_id:candidate.id,signal_id:null,evidence_type:'inference',statement:`Personal relevance: ${o.why_you||'Matched Personal Model.'}`,confidence:clamp(o.confidence),source_url:o.source_url||null});for(const unknown of(o.unknowns||[]).slice(0,4))await ins('opportunity_evidence',jwt,{user_id:user.id,candidate_id:candidate.id,signal_id:null,evidence_type:'unknown',statement:String(unknown),confidence:null,source_url:o.source_url||null})}
  const recRow={recommendation_type:'career_investigate',title:`CAREER: ${o.title}`,thesis:`${o.what_changed||''} ${o.why_you||''}`.trim(),recommended_action:o.next_action||'Verify live roles and qualifications before applying.',confidence:clamp(o.confidence),urgency:o.horizon==='today'?'normal':'low',requires_approval:true,alternatives:['continue current role','watch this occupation','investigate adjacent higher-paying occupations']};
  const prior=(await R(`recommendations?user_id=eq.${user.id}&candidate_id=eq.${candidate.id}&select=id&order=created_at.desc&limit=1`,jwt))?.[0];const recommendation=prior?await patch(`recommendations?id=eq.${prior.id}`,jwt,recRow):await ins('recommendations',jwt,{user_id:user.id,candidate_id:candidate.id,...recRow});persisted.push({candidate_id:candidate.id,recommendation_id:recommendation?.id||null,isNew,title:o.title,score:o.score});
}
await patch(`scanner_runs?id=eq.${run.id}`,jwt,{status:'completed',completed_at:new Date().toISOString(),sources_checked:1,signals_seen:Number(result?.stats?.signals_scanned||0),candidates_created:persisted.filter(x=>x.isNew).length,recommendations_created:persisted.length,metadata:{engine:'module:career-v1',module_code:'career_income',result_mode:result?.mode||null,rows_matched:result?.stats?.rows_matched||0,clusters:result?.stats?.clusters||0,surfaced:persisted.length}});
return J({ok:true,module_code:'career_income',scanner_run_id:run.id,profile_context:result?.profile_context||profile,stats:result?.stats||{},opportunities, nextBest:result?.nextBest||null,persisted});
}catch(e){if(run?.id){try{await patch(`scanner_runs?id=eq.${run.id}`,jwt,{status:'failed',completed_at:new Date().toISOString(),error:String(e).slice(0,900)})}catch{}}return J({error:String(e)},500)}});