import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const CSV="https://canadabuys.canada.ca/opendata/pub/2026-2027-awardNotice-avisAttribution.csv";
const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Cache-Control":"no-store"}});
async function F(path:string,init:RequestInit={},retry=true){const h=new Headers(init.headers||{});h.set("apikey",K);h.set("Authorization",`Bearer ${K}`);if(init.body)h.set("Content-Type","application/json");let r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:h});let t=await r.text();if(!r.ok&&retry&&r.status===401&&t.includes("JWT issued at future")){await new Promise(x=>setTimeout(x,850));r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:h});t=await r.text()}if(!r.ok)throw Error(`${r.status} ${t.slice(0,500)}`);return t?JSON.parse(t):null}
const n=(x:any)=>String(x??"").trim();
function val(o:any,ex:string[]=[],frags:string[]=[]){for(const k of ex)if(n(o[k]))return n(o[k]);const ks=Object.keys(o);for(const f of frags){const z=f.toLowerCase().replace(/[^a-z]/g,"");const k=ks.find(x=>x.toLowerCase().replace(/[^a-z]/g,"").includes(z));if(k&&n(o[k]))return n(o[k])}return""}
function num(s:string){const x=Number(String(s||"").replace(/[^0-9.-]/g,""));return Number.isFinite(x)?x:null}
function dt(s:string){if(!s)return null;const d=new Date(s);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10)}
async function hash(s:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("").slice(0,32)}
async function flush(batch:any[]){if(!batch.length)return;await F("contract_awards?on_conflict=external_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(batch.splice(0,batch.length))})}

async function piosCronSecret(){const r=await fetch(`${U}/rest/v1/system_secrets?name=eq.scheduled_intelligence&select=secret`,{headers:{apikey:K,Authorization:`Bearer ${K}`}});if(!r.ok)return "";const a=await r.json();return a?.[0]?.secret||""}
function piosSafe(a:string,b:string){if(!a||!b||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function piosAuthorized(req:Request){return piosSafe(req.headers.get("x-pios-cron-token")||"",await piosCronSecret())}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return J({error:"POST required"},405);if(!(await piosAuthorized(req)))return J({error:"unauthorized"},401);let src:any=null;try{src=(await F("world_sources?code=eq.canadabuys_awards&select=id,last_success_at"))?.[0];if(src?.last_success_at&&Date.now()-new Date(src.last_success_at).getTime()<8*3600000)return J({ok:true,skipped:true,reason:"fresh",last_success_at:src.last_success_at});const r=await fetch(CSV,{headers:{"User-Agent":"Personal-Intelligence-OS/1.0"}});if(!r.ok||!r.body)throw Error(`CanadaBuys awards ${r.status}`);
const reader=r.body.getReader(),dec=new TextDecoder();let headers:string[]|null=null,row:string[]=[],cell="",quoted=false,pendingQuote=false,scanned=0,matched=0,batch:any[]=[];const MAX_ROWS=30000;
async function finishRow(){row.push(cell);cell="";if(!headers){headers=row.map(x=>x.replace(/^\uFEFF/,"").trim());row=[];return}if(!row.some(v=>v.length)){row=[];return}scanned++;const o:any={};headers.forEach((h,i)=>o[h]=row[i]??"");row=[];const category=val(o,["procurementCategory-categorieApprovisionnement"],["procurementcategory"]);if(!category.toUpperCase().includes("CNST"))return;const title=val(o,["title-titre-eng","title-titre"],["titleeng","title"]);const desc=val(o,["awardDescription-descriptionAttribution-eng"],["awarddescriptioneng","descriptioneng","description"]);const buyer=val(o,["contractingEntityName-nomEntitContractante-eng"],["contractingentitynameeng","organizationnameeng","buyername"]);const supplier=val(o,["supplierLegalName-nomLegalFournisseur-eng"],["supplierlegalnameeng","suppliernameeng","suppliername","contractorname","vendorname","awardee"]);const region=val(o,[],["provinceterritorydeliveryeng","deliveryprovince","regioneng","province"]);const all=`${title} ${desc} ${buyer} ${region}`.toLowerCase();if(!/(alberta|calgary|edmonton|cold lake|wainwright|suffield|lake louise|banff|canmore|red deer|lethbridge|medicine hat|fort mcmurray)/i.test(all))return;const pub=val(o,["publicationDate-datePublication"],["publicationdate"]);const amount=val(o,[],["awardvalue","contractvalue","contractamount","awardamount","totalvalue"]);const curr=val(o,[],["currencyeng","currency"])||"CAD";const ref=val(o,[],["awardnoticereferencenumber","awardreference","contractnumber","solicitationnumber","tenderreferencenumber"]);const url=val(o,[],["awardnoticeurleng","noticeurleng","awardurl"]);const external=ref||await hash(`${title}|${supplier}|${pub}|${amount}`);batch.push({external_id:external,title:title||null,description:desc||null,buyer:buyer||null,supplier_name:supplier||null,region:region||null,procurement_category:category||null,publication_date:dt(pub),award_value:num(amount),currency:curr.slice(0,3).toUpperCase(),source_url:url||"https://canadabuys.canada.ca/en/tender-opportunities",raw_payload:o,updated_at:new Date().toISOString()});matched++;if(batch.length>=75)await flush(batch)}
while(scanned<MAX_ROWS){const {value,done}=await reader.read();if(done)break;const s=dec.decode(value,{stream:true});for(let i=0;i<s.length;i++){let c=s[i];if(pendingQuote){if(c==='"'){cell+='"';pendingQuote=false;continue}else{pendingQuote=false;quoted=false}}if(c==='"'){if(quoted){pendingQuote=true}else quoted=true;continue}if(c===','&&!quoted){row.push(cell);cell="";continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r')continue;await finishRow();if(scanned>=MAX_ROWS)break;continue}cell+=c}}
if(cell.length||row.length)await finishRow();await flush(batch);if(src?.id)await F(`world_sources?id=eq.${src.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({last_success_at:new Date().toISOString(),last_error:null,metadata:{purpose:"prime contractor and partner intelligence",last_scanned_rows:scanned,last_alberta_construction_awards:matched}})});return J({ok:true,scanned,alberta_construction_awards:matched,limit:MAX_ROWS})}catch(e){try{if(!src)src=(await F("world_sources?code=eq.canadabuys_awards&select=id"))?.[0];if(src?.id)await F(`world_sources?id=eq.${src.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({last_error:String(e).slice(0,500)})})}catch{}return J({error:String(e)},500)}});